// Keep protocol errors understandable in either UI language.
const EN: Record<string, string> = {
  '锦标赛不开放观赛，请报名入座': 'Tournament spectators are not allowed. Join an available seat.',
  '已淘汰，本次锦标赛不开放观赛': 'You have been eliminated. This tournament does not allow spectating.',
  '已退赛或淘汰，不能重新报名或观赛': 'Withdrawn or eliminated players cannot rejoin or spectate this tournament.',
  '锦标赛报名已截止，不开放观赛': 'Tournament registration has closed; spectating is not available.',
  '锦标赛座位已满，不开放观赛': 'All tournament seats are taken; spectating is not available.',
  '锦标赛不开放观赛，不能站起或取消入座': 'Tournament participants cannot stand up, cancel their seat or spectate.',
  '请先取消暂离再行动': 'Return from away mode before taking an action.',
  '此空座将在本手结束后移除': 'This empty seat will be removed after the current hand.',
  '暂离状态无效': 'Invalid away status.',
  '入座后才能暂离': 'Take a seat before marking yourself away.',
  '锦标赛创建后不能修改房间设置': 'Tournament settings cannot be changed after the room is created.',
  '座位布局已更新，请重试': 'The seat layout has changed. Try again.',
  '牌桌至少保留两个座位': 'A table must retain at least two seats.',
  '只能移除未占用且未预约的空座': 'Only an unoccupied, unreserved seat can be removed.',
  '至少一位玩家需选择支付 1 BB 入场': 'At least one waiting player must choose to post 1 BB to restart the table.',
  '你已经坐在这个位置': 'You already occupy this seat.',
  '请先选择座位': 'Choose a seat first.',
  '你已经可以正常参与牌局': 'You are already eligible to play.',
  '房间不存在或已过期，请重新创建或加入': 'The room has closed or expired. Create or join another room.',
  '加入凭证已失效，请重新加入房间': 'Your session has expired. Rejoin the room.',
  '玩家 ID 需为 3–36 位字母、数字、下划线或短横线': 'Player ID must contain 3–36 letters, digits, underscores or hyphens.',
  '房间已存在': 'This room already exists.',
  '牌桌人数需为 2–9 人': 'Choose 2–9 seats.',
  '初始筹码需为 20–1000 BB，单位为 0.5 BB': 'Starting chips must be 20–1000 BB in 0.5 BB increments.',
  '此玩家 ID 正在使用，请更换 ID 或恢复原标签页': 'This player ID is in use. Choose another ID or resume the original tab.',
  '此昵称正在使用，请更换昵称或恢复原标签页': 'This nickname is in use. Choose another nickname or resume the original tab.',
  '房间观战人数已满': 'The spectator limit has been reached.',
  '本桌玩家记录已满，请创建新房间': 'The player record limit has been reached. Create a new room.',
  '牌局已更新，请根据最新局面行动': 'The hand has changed. Act on the latest state.',
  '观战玩家不能行动': 'Spectators cannot take poker actions.',
  '只能在自己的行动回合使用加时卡': 'Use a time card on your own turn.',
  '不限时牌桌无需使用加时卡': 'Time cards are not needed at an unlimited-time table.',
  '没有可用的加时卡': 'No time cards are available.',
  '筹码不足，请先补码再入座': 'Rebuy chips before taking a seat.',
  '这个座位已被真人占用': 'Another player occupies this seat.',
  '这个座位已被预约': 'This seat is reserved.',
  '请等本手结束后补码': 'Wait until the hand ends before rebuying.',
  '只有输完筹码后才能补码': 'You can rebuy once your chips run out.',
  '只能展示刚结束的自己的手牌': 'You can reveal only your own cards from the completed hand.',
  '请选择要展示的底牌': 'Choose the cards to reveal.',
  '当前没有需要你选择的发牌次数': 'You do not have a runout vote in this hand.',
  '发牌次数必须为 1、2 或 3': 'Choose 1, 2 or 3 runouts.',
  '已经提交发牌次数': 'Your runout vote has already been submitted.',
  '仍有真人参与行动，暂不能加速': 'A player still has decisions to make. Fast-forward is unavailable.',
  '底牌公开设置无效': 'Invalid spectator card-sharing setting.',
  '最多只能设置 9 个席位': 'A table can have at most 9 seats.',
  '聊天消息需为 1–300 个字符': 'Chat messages must contain 1–300 characters.',
  '消息发送太快，请稍后重试': 'You are sending messages too quickly. Try again shortly.',
  '只有房主可以管理牌桌': 'Only the host can manage the table.',
  '没有可用座位': 'No seat is available.',
  '找不到这位电脑玩家': 'This computer player is unavailable.',
  '请等本手结束后再调整电脑': 'Wait until the hand ends before removing a computer.',
  '本手正在进行': 'A hand is already in progress.',
  '至少需要两位有筹码的入座玩家': 'At least two seated players with chips are needed.',
  '未知房间指令': 'Unknown room command.',
  '牌桌模式无效': 'Invalid table mode.',
  '行动时间需为不限时或 20、30、40、50、60 秒': 'Choose unlimited action time or 20, 30, 40, 50 or 60 seconds.',
  '升盲间隔需为 1–60 分钟': 'Blind levels must last an integer number of minutes from 1 to 60.',
  '锦标赛开始后席位和参赛名单固定，不能补码或调整席位': 'Tournament entries and seats are locked after the start. Rebuys and seat changes are unavailable.',
  '报名与重购截止需为升盲 0–10 次后': 'Registration and rebuys must close after 0–10 blind increases.',
  '已报名的锦标赛席位不能移动、取消或替换': 'Registered tournament seats cannot be moved, cancelled or replaced.',
  '锦标赛报名与重购已截止': 'Tournament registration and rebuys are closed.',
  '已退赛或淘汰，不能重新报名': 'Withdrawn or eliminated entries cannot register again.',
  '请先报名入座': 'Register at an empty seat first.',
  '锦标赛只能报名空座，不能替换参赛玩家': 'Tournament entries require an empty seat. Existing entrants cannot be replaced.',
  '当前没有可操作的对应牌局': 'This hand is no longer accepting actions.',
  '座位无效': 'Invalid seat.',
  '行动格式错误': 'Invalid action format.',
  '现在不是你的行动轮次': 'It is not your turn.',
  '有未跟注的下注，不能过牌': 'You must call or fold when facing a bet.',
  '当前无需跟注，请过牌': 'There is no bet to call. Check instead.',
  '加注金额无效，或本轮加注权尚未重新开放': 'Invalid raise amount, or betting has not reopened.',
  '无效行动': 'Invalid action.',
  '请输入昵称': 'Enter a nickname.',
  '昵称需为 1–16 个可见字符': 'Nickname must contain 1–16 visible characters.',
  '请使用 JSON 请求': 'Use a JSON request.',
  '缺少请求内容': 'Request body is missing.',
  '请求内容过长': 'Request body is too large.',
  '请求内容无效': 'Invalid request body.',
  '请从本站发起请求': 'Send requests from this site.',
  '房间地址无效': 'Invalid room address.',
  '请求方法无效': 'Invalid request method.',
  '房间创建繁忙，请重试': 'Room creation is busy. Try again.',
}
export const englishError = (message: string) => EN[message] ?? 'The request could not be completed. Refresh the room and try again.'
